name: 'webhook-notifications'
description: 'webhook-notifications'
branding:
  icon: 'check-square'
  color: 'orange'
inputs:
  discord-webhook:
    description: >-
      Specific discord-webhook URL to send the notification.
    required: true
  message-color:
    description: >-
      Message's color.
    required: false
  message-icon:
    description: >-
      Message's icon.
    required: false
  message-username: 
      description: >-
      Message's username.
    required: false
  message-title: 
      description: >-
      Message's title.
    required: false
  message-text: 
      description: >-
      Message's text.
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
